name: CI/CD for Hello World JS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          echo "No dependencies to install for static HTML/JS/CSS"

      - name: Run tests
        run: |
          echo "No test file found for static site. Skipping tests."

      - name: Build Docker image
        run: |
          docker build -t helloworld:latest .
      # Optional: Add Docker Hub push or deployment step here
