name: CI/CD for Typing Speed Game
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          if [ -f test.py ]; then python test.py; fi
      - name: Build Docker image
        run: |
          docker build -t typing-speed-game:latest .
      # You can add steps here to push to Docker Hub or deploy to a server/cloud